---
trigger:
  - main

parameters:
  - name: days
    type: object
    default: ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5', 'Day 6', 'Day 7', 'Day 8', 'Day 9', 'Day 10']

jobs:
  - job: Advent_Of_Code
    strategy:
      matrix:
        visual_studio_2019:
          imageName: 'windows-2019'
          generator: Visual Studio 16 2019
        visual_studio_2022:
          imageName: 'windows-2022'
          generator: Visual Studio 17 2022
        xcode:
          imageName: 'macOS-11'
          generator: Xcode
        unix_makefiles:
          imageName: 'ubuntu-20.04'
          generator: Unix Makefiles
    pool:
      vmImage: $(imageName)
    steps:
      - ${{ each day in parameters.days }}:
          - template: .azure-pipeline/build.yml
            parameters:
              generator: $(generator)
              root_directory: ${{ day }}
